# Stage 1: Build Stage
FROM node:16-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Stage 2: Production Stage
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=build /app /app

# Install only production dependencies (to reduce image size)
RUN npm install --production

# Expose the port that the application will run on
EXPOSE 3000

# Command to run the application
CMD ["node", "server.js"]
